import { Attribute, Category, Fit, Product } from "./types";

export const products: Product[] = [
  {
    id: "7",
    name: "极简御寒单品",
    category: Category.RECOMMEND,
    attribute: Attribute.FLEECE,
    fit: Fit.OVERSIZED,
    price: 899,
    originalPrice: 1299,
    sales: 88,
    isNew: true,
    images: [
      "/cms/goose/products/pro-1.jpg",
      "/cms/goose/products/detail/商品主图_1.png",
    ],
    tags: ["90白鸭绒", "冬季保暖", "防泼水"],
    description: "高性能御寒单品。专为极寒天气设计，兼具极简美学。",
    material: "Gore-Tex / 90% 白鸭绒",
    colors: ["曜石黑", "浆果紫", "灰绿色"],
    sizes: ["M", "L", "XL", "XXL"],
    detailImages: [
      "/cms/goose/products/detail/详情1 (1).jpg",
      "/cms/goose/products/detail/详情1 (2).jpg",
      "/cms/goose/products/detail/详情1 (3).jpg",
      "/cms/goose/products/detail/详情1 (4).jpg",
      "/cms/goose/products/detail/详情1 (5).jpg",
      "/cms/goose/products/detail/详情1 (6).jpg",
      "/cms/goose/products/detail/详情1 (7).jpg",
      "/cms/goose/products/detail/详情1 (8).jpg",
      "/cms/goose/products/detail/详情1 (9).jpg",
    ],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "8",
    name: "都市解构单品",
    category: Category.RECOMMEND,
    attribute: Attribute.FLEECE,
    fit: Fit.LOOSE,
    price: 899,
    originalPrice: 1299,
    sales: 156,
    isNew: true,
    images: [
      "/cms/goose/products/pro-2.jpg",
      "/cms/goose/products/detail/商品主图_2.jpg",
    ],
    tags: ["解构设计", "轻量化", "现代感"],
    description:
      "一款不在此消彼长的设计单品。结构感编织面料赋予其独特质感，同时保持温暖。",
    material: "科技尼龙",
    colors: ["米白", "炭灰"],
    sizes: ["M", "L", "XL"],
    detailImages: [
      "/cms/goose/products/detail/详情1 (1).jpg",
      "/cms/goose/products/detail/详情1 (2).jpg",
      "/cms/goose/products/detail/详情1 (3).jpg",
      "/cms/goose/products/detail/详情1 (4).jpg",
      "/cms/goose/products/detail/详情1 (5).jpg",
      "/cms/goose/products/detail/详情1 (6).jpg",
      "/cms/goose/products/detail/详情1 (7).jpg",
      "/cms/goose/products/detail/详情1 (8).jpg",
      "/cms/goose/products/detail/详情1 (9).jpg",
    ],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "1",
    name: "经典廓形外套",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.OVERSIZED,
    price: 899,
    originalPrice: 1299,
    sales: 120,
    isNew: true,
    isComingSoon: true,
    images: ["/cms/goose/ads/1.jpg", "/cms/goose/ads/2.jpg"],
    tags: ["优质羊毛", "廓形", "冬季必备"],
    description:
      "采用优质混纺面料制成的结构感单品。为看重温暖与建筑剪影的现代都市人设计。",
    material: "80% 羊毛, 20% 羊绒",
    colors: ["炭黑", "杂灰"],
    sizes: ["S", "M", "L"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "2",
    name: "极简基础单品",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 259,
    originalPrice: 359,
    sales: 450,
    isNew: true,
    isComingSoon: true,
    images: ["/cms/goose/ads/2.jpg", "/cms/goose/ads/3.jpg"],
    tags: ["有机棉", "日常", "透气"],
    description: "衣橱的基石。采用高品质面料，质感厚实且透气。",
    material: "100% 有机棉",
    colors: ["白", "黑", "沙色"],
    sizes: ["S", "M", "L", "XL"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "3",
    name: "垂感设计单品",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.LOOSE,
    price: 499,
    originalPrice: 699,
    sales: 320,
    isNew: false,
    isComingSoon: true,
    images: ["/cms/goose/ads/3.jpg"],
    tags: ["垂感", "舒适", "百搭"],
    description: "随行而动的垂感单品。深褶裥设计与宽松版型，打造不费力的优雅。",
    material: "聚酯纤维混纺",
    colors: ["黑", "藏青"],
    sizes: ["S", "M", "L"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "4",
    name: "现代针织单品",
    category: Category.NEW,
    attribute: Attribute.FLEECE,
    fit: Fit.OVERSIZED,
    price: 399,
    originalPrice: 599,
    sales: 280,
    isNew: false,
    isComingSoon: true,
    images: ["/cms/goose/ads/4.jpg"],
    tags: ["科技面料", "保暖", "现代"],
    description:
      "重新构想的日常单品。利落线条，隐藏式口袋，以及保持挺括的面料。",
    material: "棉/聚酯纤维混纺",
    colors: ["黑", "水泥灰"],
    sizes: ["M", "L", "XL"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "5",
    name: "建筑感剪裁单品",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 799,
    originalPrice: 1099,
    sales: 150,
    isNew: true,
    isComingSoon: true,
    images: ["/cms/goose/ads/5.jpg", "/cms/goose/ads/6.jpg"],
    tags: ["剪裁", "利落", "通勤"],
    description:
      "利落剪裁相遇现代舒适。一款看起来专业但穿起来轻松的无结构单品。",
    material: "羊毛混纺",
    colors: ["黑", "午夜蓝"],
    sizes: ["S", "M", "L", "XL"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
  {
    id: "6",
    name: "机能风设计单品",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.CUFFED,
    price: 359,
    originalPrice: 459,
    sales: 500,
    isNew: false,
    isComingSoon: true,
    images: ["/cms/goose/ads/6.jpg"],
    tags: ["机能", "街头", "耐磨"],
    description: "将功能性口袋融入流畅廓形。实用而不臃肿。",
    material: "尼龙/棉",
    colors: ["黑", "橄榄绿"],
    sizes: ["M", "L", "XL"],
    tmallUrl:
      "https://amidrajk.tmall.com/shop/view_shop.htm?spm=pc_detail.30350276.shop_popup_block.dentershop.296f7dd63PbT10",
  },
];
