import { Attribute, Category, Fit, Product } from "./types";

export const products: Product[] = [
  {
    id: "new-26",
    name: "正品AMI DRAJK拼接棉服男款秋冬季新款设计感翻领休闲夹克宽松",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1088,
    originalPrice: 1650,
    sales: 0,
    isNew: true,
    images: [
      "/products-new/pro-26/main/main1.jpg",
      "/products-new/pro-26/main/main2.jpg",
      "/products-new/pro-26/main/main3.jpg",
      "/products-new/pro-26/main/main4.jpg",
      "/products-new/pro-26/main/main5.jpg",
    ],
    tags: ["新品", "推荐"],
    description: "正品AMI DRAJK拼接棉服男款秋冬季新款设计感翻领休闲夹克宽松",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-26/detail/detail1.jpg",
      "/products-new/pro-26/detail/detail2.jpg",
      "/products-new/pro-26/detail/detail3.jpg",
      "/products-new/pro-26/detail/detail4.jpg",
      "/products-new/pro-26/detail/detail5.jpg",
      "/products-new/pro-26/detail/detail6.jpg",
      "/products-new/pro-26/detail/detail7.jpg",
      "/products-new/pro-26/detail/detail8.jpg",
      "/products-new/pro-26/detail/detail9.jpg",
      "/products-new/pro-26/detail/detail10.jpg",
      "/products-new/pro-26/detail/detail11.jpg",
      "/products-new/pro-26/detail/detail12.jpg",
      "/products-new/pro-26/detail/detail13.jpg",
      "/products-new/pro-26/detail/detail14.jpg",
      "/products-new/pro-26/detail/detail15.jpg",
      "/products-new/pro-26/detail/detail16.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-1",
    name: "AMI DRAJK 系列新品 1",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 860,
    originalPrice: 1140,
    sales: 381,
    isNew: true,
    images: [
      "/products-new/pro-1/main/main01.jpg",
      "/products-new/pro-1/main/main02.jpg",
      "/products-new/pro-1/main/main03.jpg",
      "/products-new/pro-1/main/main04.jpg",
      "/products-new/pro-1/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 1，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-1/detail/detail01.jpg",
      "/products-new/pro-1/detail/detail02.jpg",
      "/products-new/pro-1/detail/detail03.jpg",
      "/products-new/pro-1/detail/detail04.jpg",
      "/products-new/pro-1/detail/detail05.jpg",
      "/products-new/pro-1/detail/detail06.jpg",
      "/products-new/pro-1/detail/detail07.jpg",
      "/products-new/pro-1/detail/detail08.jpg",
      "/products-new/pro-1/detail/detail09.jpg",
      "/products-new/pro-1/detail/detail10.jpg",
      "/products-new/pro-1/detail/detail11.jpg",
      "/products-new/pro-1/detail/detail12.jpg",
      "/products-new/pro-1/detail/detail13.jpg",
      "/products-new/pro-1/detail/detail14.jpg",
      "/products-new/pro-1/detail/detail15.jpg",
      "/products-new/pro-1/detail/detail16.jpg",
      "/products-new/pro-1/detail/detail17.jpg",
      "/products-new/pro-1/detail/detail18.jpg",
      "/products-new/pro-1/detail/detail19.jpg",
      "/products-new/pro-1/detail/detail20.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-2",
    name: "AMI DRAJK 系列新品 2",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1250,
    originalPrice: 1380,
    sales: 499,
    isNew: true,
    images: [
      "/products-new/pro-2/main/main01.jpg",
      "/products-new/pro-2/main/main02.jpg",
      "/products-new/pro-2/main/main03.jpg",
      "/products-new/pro-2/main/main04.jpg",
      "/products-new/pro-2/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 2，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-2/detail/detail02.jpg",
      "/products-new/pro-2/detail/detail03.jpg",
      "/products-new/pro-2/detail/detail04.jpg",
      "/products-new/pro-2/detail/detail05.jpg",
      "/products-new/pro-2/detail/detail06.jpg",
      "/products-new/pro-2/detail/detail07.jpg",
      "/products-new/pro-2/detail/detail08.jpg",
      "/products-new/pro-2/detail/detail09.jpg",
      "/products-new/pro-2/detail/detail10.png",
      "/products-new/pro-2/detail/detail11.jpg",
      "/products-new/pro-2/detail/detail12.jpg",
      "/products-new/pro-2/detail/detail13.jpg",
      "/products-new/pro-2/detail/detail14.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-3",
    name: "AMI DRAJK 系列新品 3",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1088,
    originalPrice: 1320,
    sales: 253,
    isNew: true,
    images: [
      "/products-new/pro-3/main/main.jpg",
      "/products-new/pro-3/main/main1.jpg",
      "/products-new/pro-3/main/main2.jpg",
      "/products-new/pro-3/main/main3.jpg",
      "/products-new/pro-3/main/main4.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 3，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-3/detail/01.jpg",
      "/products-new/pro-3/detail/02.jpg",
      "/products-new/pro-3/detail/03.jpg",
      "/products-new/pro-3/detail/04.jpg",
      "/products-new/pro-3/detail/05.jpg",
      "/products-new/pro-3/detail/06.jpg",
      "/products-new/pro-3/detail/07.jpg",
      "/products-new/pro-3/detail/08.jpg",
      "/products-new/pro-3/detail/09.jpg",
      "/products-new/pro-3/detail/10.jpg",
      "/products-new/pro-3/detail/11.jpg",
      "/products-new/pro-3/detail/12.jpg",
      "/products-new/pro-3/detail/13.jpg",
      "/products-new/pro-3/detail/14.jpg",
      "/products-new/pro-3/detail/15.jpg",
      "/products-new/pro-3/detail/16.jpg",
      "/products-new/pro-3/detail/17.jpg",
      "/products-new/pro-3/detail/18.jpg",
      "/products-new/pro-3/detail/19.jpg",
      "/products-new/pro-3/detail/20.jpg",
      "/products-new/pro-3/detail/21.jpg",
      "/products-new/pro-3/detail/22.jpg",
      "/products-new/pro-3/detail/23.jpg",
      "/products-new/pro-3/detail/24.jpg",
      "/products-new/pro-3/detail/25.jpg",
      "/products-new/pro-3/detail/26.jpg",
      "/products-new/pro-3/detail/27.jpg",
      "/products-new/pro-3/detail/28.jpg",
      "/products-new/pro-3/detail/29.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-4",
    name: "AMI DRAJK 系列新品 4",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1398,
    originalPrice: 1750,
    sales: 422,
    isNew: true,
    images: [
      "/products-new/pro-4/main/main01.jpg",
      "/products-new/pro-4/main/main02.jpg",
      "/products-new/pro-4/main/main03.jpg",
      "/products-new/pro-4/main/main04.jpg",
      "/products-new/pro-4/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 4，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-4/detail/detail01.jpg",
      "/products-new/pro-4/detail/detail02.jpg",
      "/products-new/pro-4/detail/detail03.jpg",
      "/products-new/pro-4/detail/detail04.jpg",
      "/products-new/pro-4/detail/detail05.jpg",
      "/products-new/pro-4/detail/detail06.jpg",
      "/products-new/pro-4/detail/detail07.jpg",
      "/products-new/pro-4/detail/detail08.jpg",
      "/products-new/pro-4/detail/detail09.jpg",
      "/products-new/pro-4/detail/detail10.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-5",
    name: "AMI DRAJK 系列新品 5",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1080,
    originalPrice: 1510,
    sales: 79,
    isNew: true,
    images: [
      "/products-new/pro-5/main/main01.jpg",
      "/products-new/pro-5/main/main02.jpg",
      "/products-new/pro-5/main/main03.jpg",
      "/products-new/pro-5/main/main04.jpg",
      "/products-new/pro-5/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 5，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-5/detail/detail02.jpg",
      "/products-new/pro-5/detail/detail03.jpg",
      "/products-new/pro-5/detail/detail04.jpg",
      "/products-new/pro-5/detail/detail05.jpg",
      "/products-new/pro-5/detail/detail06.jpg",
      "/products-new/pro-5/detail/detail07.jpg",
      "/products-new/pro-5/detail/detail08.jpg",
      "/products-new/pro-5/detail/detail09.jpg",
      "/products-new/pro-5/detail/detail10.jpg",
      "/products-new/pro-5/detail/detail11.jpg",
      "/products-new/pro-5/detail/detail12.jpg",
      "/products-new/pro-5/detail/detail13.jpg",
      "/products-new/pro-5/detail/detail14.jpg",
      "/products-new/pro-5/detail/detail15.jpg",
      "/products-new/pro-5/detail/detail16.jpg",
      "/products-new/pro-5/detail/detail17.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-6",
    name: "AMI DRAJK 系列新品 6",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1100,
    originalPrice: 1560,
    sales: 227,
    isNew: true,
    images: [
      "/products-new/pro-6/main/main01.jpg",
      "/products-new/pro-6/main/main02.jpg",
      "/products-new/pro-6/main/main03.jpg",
      "/products-new/pro-6/main/main04.jpg",
      "/products-new/pro-6/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 6，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-6/detail/detail02.jpg",
      "/products-new/pro-6/detail/detail03.jpg",
      "/products-new/pro-6/detail/detail04.jpg",
      "/products-new/pro-6/detail/detail05.jpg",
      "/products-new/pro-6/detail/detail06.jpg",
      "/products-new/pro-6/detail/detail07.jpg",
      "/products-new/pro-6/detail/detail08.jpg",
      "/products-new/pro-6/detail/detail09.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-7",
    name: "AMI DRAJK 系列新品 7",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1450,
    originalPrice: 1670,
    sales: 306,
    isNew: true,
    images: [
      "/products-new/pro-7/main/main01.jpg",
      "/products-new/pro-7/main/main02.jpg",
      "/products-new/pro-7/main/main03.jpg",
      "/products-new/pro-7/main/main04.jpg",
      "/products-new/pro-7/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 7，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-7/detail/detail02.jpg",
      "/products-new/pro-7/detail/detail03.jpg",
      "/products-new/pro-7/detail/detail04.jpg",
      "/products-new/pro-7/detail/detail05.jpg",
      "/products-new/pro-7/detail/detail06.jpg",
      "/products-new/pro-7/detail/detail07.jpg",
      "/products-new/pro-7/detail/detail08.jpg",
      "/products-new/pro-7/detail/detail09.jpg",
      "/products-new/pro-7/detail/detail10.jpg",
      "/products-new/pro-7/detail/detail11.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-8",
    name: "AMI DRAJK 系列新品 8",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1298,
    originalPrice: 1850,
    sales: 370,
    isNew: true,
    images: [
      "/products-new/pro-8/main/main01.jpg",
      "/products-new/pro-8/main/main02.jpg",
      "/products-new/pro-8/main/main03.jpg",
      "/products-new/pro-8/main/main04.jpg",
      "/products-new/pro-8/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 8，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-8/detail/detail02.jpg",
      "/products-new/pro-8/detail/detail03.jpg",
      "/products-new/pro-8/detail/detail04.jpg",
      "/products-new/pro-8/detail/detail05.jpg",
      "/products-new/pro-8/detail/detail06.jpg",
      "/products-new/pro-8/detail/detail07.jpg",
      "/products-new/pro-8/detail/detail08.jpg",
      "/products-new/pro-8/detail/detail09.jpg",
      "/products-new/pro-8/detail/detail10.jpg",
      "/products-new/pro-8/detail/detail11.jpg",
      "/products-new/pro-8/detail/detail12.jpg",
      "/products-new/pro-8/detail/detail13.jpg",
      "/products-new/pro-8/detail/detail14.jpg",
      "/products-new/pro-8/detail/detail15.jpg",
      "/products-new/pro-8/detail/detail16.jpg",
      "/products-new/pro-8/detail/detail17.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-9",
    name: "AMI DRAJK 系列新品 9",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 940,
    originalPrice: 1170,
    sales: 276,
    isNew: true,
    images: [
      "/products-new/pro-9/main/main01.jpg",
      "/products-new/pro-9/main/main02.jpg",
      "/products-new/pro-9/main/main03.jpg",
      "/products-new/pro-9/main/main04.jpg",
      "/products-new/pro-9/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 9，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-9/detail/detail02.jpg",
      "/products-new/pro-9/detail/detail03.jpg",
      "/products-new/pro-9/detail/detail04.jpg",
      "/products-new/pro-9/detail/detail05.jpg",
      "/products-new/pro-9/detail/detail06.jpg",
      "/products-new/pro-9/detail/detail07.jpg",
      "/products-new/pro-9/detail/detail08.jpg",
      "/products-new/pro-9/detail/detail09.jpg",
      "/products-new/pro-9/detail/detail10.jpg",
      "/products-new/pro-9/detail/detail11.jpg",
      "/products-new/pro-9/detail/detail12.jpg",
      "/products-new/pro-9/detail/detail13.jpg",
      "/products-new/pro-9/detail/detail14.jpg",
      "/products-new/pro-9/detail/detail15.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-10",
    name: "AMI DRAJK 系列新品 10",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1118,
    originalPrice: 1260,
    sales: 113,
    isNew: true,
    images: [
      "/products-new/pro-10/main/main01.jpg",
      "/products-new/pro-10/main/main02.jpg",
      "/products-new/pro-10/main/main03.jpg",
      "/products-new/pro-10/main/main04.jpg",
      "/products-new/pro-10/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 10，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-10/detail/detail02.jpg",
      "/products-new/pro-10/detail/detail03.jpg",
      "/products-new/pro-10/detail/detail04.jpg",
      "/products-new/pro-10/detail/detail05.jpg",
      "/products-new/pro-10/detail/detail06.jpg",
      "/products-new/pro-10/detail/detail07.jpg",
      "/products-new/pro-10/detail/detail08.jpg",
      "/products-new/pro-10/detail/detail09.jpg",
      "/products-new/pro-10/detail/detail10.jpg",
      "/products-new/pro-10/detail/detail11.jpg",
      "/products-new/pro-10/detail/detail12.jpg",
      "/products-new/pro-10/detail/detail13.jpg",
      "/products-new/pro-10/detail/detail14.jpg",
      "/products-new/pro-10/detail/detail15.jpg",
      "/products-new/pro-10/detail/detail16.jpg",
      "/products-new/pro-10/detail/detail17.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-11",
    name: "AMI DRAJK 系列新品 11",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 918,
    originalPrice: 1320,
    sales: 316,
    isNew: true,
    images: [
      "/products-new/pro-11/main/main1.png",
      "/products-new/pro-11/main/main2.jpg",
      "/products-new/pro-11/main/main3.jpg",
      "/products-new/pro-11/main/main4.jpg",
      "/products-new/pro-11/main/main5.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 11，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-11/detail/detai13.jpg",
      "/products-new/pro-11/detail/detail.jpg",
      "/products-new/pro-11/detail/detail.png",
      "/products-new/pro-11/detail/detail1.jpg",
      "/products-new/pro-11/detail/detail10.jpg",
      "/products-new/pro-11/detail/detail11.jpg",
      "/products-new/pro-11/detail/detail12.jpg",
      "/products-new/pro-11/detail/detail14.jpg",
      "/products-new/pro-11/detail/detail2.jpg",
      "/products-new/pro-11/detail/detail3.jpg",
      "/products-new/pro-11/detail/detail4.jpg",
      "/products-new/pro-11/detail/detail5.jpg",
      "/products-new/pro-11/detail/detail6.jpg",
      "/products-new/pro-11/detail/detail7.jpg",
      "/products-new/pro-11/detail/detail8.jpg",
      "/products-new/pro-11/detail/detail9.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-12",
    name: "AMI DRAJK 系列新品 12",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1338,
    originalPrice: 1810,
    sales: 306,
    isNew: true,
    images: [
      "/products-new/pro-12/main/main01.jpg",
      "/products-new/pro-12/main/main02.jpg",
      "/products-new/pro-12/main/main03.jpg",
      "/products-new/pro-12/main/main04.jpg",
      "/products-new/pro-12/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 12，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-12/detail/detail02.jpg",
      "/products-new/pro-12/detail/detail03.jpg",
      "/products-new/pro-12/detail/detail04.jpg",
      "/products-new/pro-12/detail/detail05.jpg",
      "/products-new/pro-12/detail/detail06.jpg",
      "/products-new/pro-12/detail/detail07.jpg",
      "/products-new/pro-12/detail/detail08.jpg",
      "/products-new/pro-12/detail/detail09.jpg",
      "/products-new/pro-12/detail/detail10.jpg",
      "/products-new/pro-12/detail/detail11.jpg",
      "/products-new/pro-12/detail/detail12.jpg",
      "/products-new/pro-12/detail/detail13.jpg",
      "/products-new/pro-12/detail/detail14.jpg",
      "/products-new/pro-12/detail/detail15.jpg",
      "/products-new/pro-12/detail/detail16.jpg",
      "/products-new/pro-12/detail/detail17.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-13",
    name: "AMI DRAJK 系列新品 13",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1118,
    originalPrice: 1510,
    sales: 240,
    isNew: true,
    images: [
      "/products-new/pro-13/main/main01.jpg",
      "/products-new/pro-13/main/main02.jpg",
      "/products-new/pro-13/main/main03.jpg",
      "/products-new/pro-13/main/main04.jpg",
      "/products-new/pro-13/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 13，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-13/detail/detail02.jpg",
      "/products-new/pro-13/detail/detail03.jpg",
      "/products-new/pro-13/detail/detail04.jpg",
      "/products-new/pro-13/detail/detail05.jpg",
      "/products-new/pro-13/detail/detail06.jpg",
      "/products-new/pro-13/detail/detail07.jpg",
      "/products-new/pro-13/detail/detail08.jpg",
      "/products-new/pro-13/detail/detail09.jpg",
      "/products-new/pro-13/detail/detail10.jpg",
      "/products-new/pro-13/detail/detail11.jpg",
      "/products-new/pro-13/detail/detail12.jpg",
      "/products-new/pro-13/detail/detail13.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-14",
    name: "AMI DRAJK 系列新品 14",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1050,
    originalPrice: 1480,
    sales: 450,
    isNew: true,
    images: [
      "/products-new/pro-14/main/main01.jpg",
      "/products-new/pro-14/main/main02.jpg",
      "/products-new/pro-14/main/main03.jpg",
      "/products-new/pro-14/main/main04.jpg",
      "/products-new/pro-14/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 14，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-14/detail/detail01.jpg",
      "/products-new/pro-14/detail/detail02.jpg",
      "/products-new/pro-14/detail/detail03.jpg",
      "/products-new/pro-14/detail/detail04.jpg",
      "/products-new/pro-14/detail/detail05.jpg",
      "/products-new/pro-14/detail/detail06.jpg",
      "/products-new/pro-14/detail/detail07.jpg",
      "/products-new/pro-14/detail/detail08.jpg",
      "/products-new/pro-14/detail/detail09.jpg",
      "/products-new/pro-14/detail/detail10.jpg",
      "/products-new/pro-14/detail/detail11.jpg",
      "/products-new/pro-14/detail/detail12.jpg",
      "/products-new/pro-14/detail/detail13.jpg",
      "/products-new/pro-14/detail/detail14.jpg",
      "/products-new/pro-14/detail/detail15.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-15",
    name: "AMI DRAJK 系列新品 15",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1098,
    originalPrice: 1680,
    sales: 407,
    isNew: true,
    images: [
      "/products-new/pro-15/main/main01.jpg",
      "/products-new/pro-15/main/main02.jpg",
      "/products-new/pro-15/main/main03.jpg",
      "/products-new/pro-15/main/main04.jpg",
      "/products-new/pro-15/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 15，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-15/detail/detail01.jpg",
      "/products-new/pro-15/detail/detail02.jpg",
      "/products-new/pro-15/detail/detail03.jpg",
      "/products-new/pro-15/detail/detail04.jpg",
      "/products-new/pro-15/detail/detail05.jpg",
      "/products-new/pro-15/detail/detail06.jpg",
      "/products-new/pro-15/detail/detail07.jpg",
      "/products-new/pro-15/detail/detail08.jpg",
      "/products-new/pro-15/detail/detail09.jpg",
      "/products-new/pro-15/detail/detail10.jpg",
      "/products-new/pro-15/detail/detail11.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-16",
    name: "AMI DRAJK 系列新品 16",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 878,
    originalPrice: 1430,
    sales: 320,
    isNew: true,
    images: [
      "/products-new/pro-16/main/main01.jpg",
      "/products-new/pro-16/main/main02.jpg",
      "/products-new/pro-16/main/main03.jpg",
      "/products-new/pro-16/main/main04.jpg",
      "/products-new/pro-16/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 16，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-16/detail/detail01.jpg",
      "/products-new/pro-16/detail/detail02.jpg",
      "/products-new/pro-16/detail/detail03.jpg",
      "/products-new/pro-16/detail/detail04.jpg",
      "/products-new/pro-16/detail/detail05.jpg",
      "/products-new/pro-16/detail/detail06.jpg",
      "/products-new/pro-16/detail/detail07.jpg",
      "/products-new/pro-16/detail/detail08.jpg",
      "/products-new/pro-16/detail/detail09.jpg",
      "/products-new/pro-16/detail/detail10.jpg",
      "/products-new/pro-16/detail/detail11.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-17",
    name: "AMI DRAJK 系列新品 17",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1270,
    originalPrice: 1400,
    sales: 433,
    isNew: true,
    images: [
      "/products-new/pro-17/main/main01.jpg",
      "/products-new/pro-17/main/main02.jpg",
      "/products-new/pro-17/main/main03.jpg",
      "/products-new/pro-17/main/main04.jpg",
      "/products-new/pro-17/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 17，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-17/detail/detail02.jpg",
      "/products-new/pro-17/detail/detail03.jpg",
      "/products-new/pro-17/detail/detail04.jpg",
      "/products-new/pro-17/detail/detail05.jpg",
      "/products-new/pro-17/detail/detail06.jpg",
      "/products-new/pro-17/detail/detail07.jpg",
      "/products-new/pro-17/detail/detail08.jpg",
      "/products-new/pro-17/detail/detail09.jpg",
      "/products-new/pro-17/detail/detail10.jpg",
      "/products-new/pro-17/detail/detail11.jpg",
      "/products-new/pro-17/detail/detail12.jpg",
      "/products-new/pro-17/detail/detail13.jpg",
      "/products-new/pro-17/detail/detail14.jpg",
      "/products-new/pro-17/detail/detail15.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-18",
    name: "AMI DRAJK 系列新品 18",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1230,
    originalPrice: 1430,
    sales: 324,
    isNew: true,
    images: [
      "/products-new/pro-18/main/main01.jpg",
      "/products-new/pro-18/main/main02.jpg",
      "/products-new/pro-18/main/main03.jpg",
      "/products-new/pro-18/main/main04.jpg",
      "/products-new/pro-18/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 18，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-18/detail/detail01.jpg",
      "/products-new/pro-18/detail/detail02.jpg",
      "/products-new/pro-18/detail/detail03.jpg",
      "/products-new/pro-18/detail/detail04.jpg",
      "/products-new/pro-18/detail/detail05.jpg",
      "/products-new/pro-18/detail/detail06.jpg",
      "/products-new/pro-18/detail/detail07.jpg",
      "/products-new/pro-18/detail/detail08.jpg",
      "/products-new/pro-18/detail/detail09.jpg",
      "/products-new/pro-18/detail/detail10.jpg",
      "/products-new/pro-18/detail/detail11.jpg",
      "/products-new/pro-18/detail/detail12.jpg",
      "/products-new/pro-18/detail/detail13.jpg",
      "/products-new/pro-18/detail/detail14.jpg",
      "/products-new/pro-18/detail/detail15.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-19",
    name: "AMI DRAJK 系列新品 19",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1470,
    originalPrice: 1590,
    sales: 445,
    isNew: true,
    images: [
      "/products-new/pro-19/main/main01.jpg",
      "/products-new/pro-19/main/main02.jpg",
      "/products-new/pro-19/main/main03.jpg",
      "/products-new/pro-19/main/main04.jpg",
      "/products-new/pro-19/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 19，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-19/detail/detail02.jpg",
      "/products-new/pro-19/detail/detail03.jpg",
      "/products-new/pro-19/detail/detail04.jpg",
      "/products-new/pro-19/detail/detail05.jpg",
      "/products-new/pro-19/detail/detail06.jpg",
      "/products-new/pro-19/detail/detail07.jpg",
      "/products-new/pro-19/detail/detail08.jpg",
      "/products-new/pro-19/detail/detail09.jpg",
      "/products-new/pro-19/detail/detail10.jpg",
      "/products-new/pro-19/detail/detail11.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-20",
    name: "AMI DRAJK 系列新品 20",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1250,
    originalPrice: 1480,
    sales: 470,
    isNew: true,
    images: [
      "/products-new/pro-20/main/main01.jpg",
      "/products-new/pro-20/main/main02.jpg",
      "/products-new/pro-20/main/main03.jpg",
      "/products-new/pro-20/main/main04.jpg",
      "/products-new/pro-20/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 20，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-20/detail/detail02.jpg",
      "/products-new/pro-20/detail/detail03.jpg",
      "/products-new/pro-20/detail/detail04.jpg",
      "/products-new/pro-20/detail/detail05.jpg",
      "/products-new/pro-20/detail/detail06.jpg",
      "/products-new/pro-20/detail/detail07.jpg",
      "/products-new/pro-20/detail/detail08.jpg",
      "/products-new/pro-20/detail/detail09.jpg",
      "/products-new/pro-20/detail/detail10.jpg",
      "/products-new/pro-20/detail/detail11.jpg",
      "/products-new/pro-20/detail/detail12.jpg",
      "/products-new/pro-20/detail/detail13.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-21",
    name: "AMI DRAJK 系列新品 21",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1420,
    originalPrice: 1550,
    sales: 200,
    isNew: true,
    images: [
      "/products-new/pro-21/main/main01.jpg",
      "/products-new/pro-21/main/main02.jpg",
      "/products-new/pro-21/main/main03.jpg",
      "/products-new/pro-21/main/main04.jpg",
      "/products-new/pro-21/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 21，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-21/detail/detail02.jpg",
      "/products-new/pro-21/detail/detail03.jpg",
      "/products-new/pro-21/detail/detail04.jpg",
      "/products-new/pro-21/detail/detail05.jpg",
      "/products-new/pro-21/detail/detail06.jpg",
      "/products-new/pro-21/detail/detail07.jpg",
      "/products-new/pro-21/detail/detail08.jpg",
      "/products-new/pro-21/detail/detail09.jpg",
      "/products-new/pro-21/detail/detail10.jpg",
      "/products-new/pro-21/detail/detail11.jpg",
      "/products-new/pro-21/detail/detail12.jpg",
      "/products-new/pro-21/detail/detail13.jpg",
      "/products-new/pro-21/detail/detail14.jpg",
      "/products-new/pro-21/detail/detail15.jpg",
      "/products-new/pro-21/detail/detail16.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-22",
    name: "AMI DRAJK 系列新品 22",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1170,
    originalPrice: 1440,
    sales: 214,
    isNew: true,
    images: [
      "/products-new/pro-22/main/main01.jpg",
      "/products-new/pro-22/main/main02.jpg",
      "/products-new/pro-22/main/main03.jpg",
      "/products-new/pro-22/main/main04.jpg",
      "/products-new/pro-22/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 22，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-22/detail/detail02.jpg",
      "/products-new/pro-22/detail/detail03.jpg",
      "/products-new/pro-22/detail/detail04.jpg",
      "/products-new/pro-22/detail/detail05.jpg",
      "/products-new/pro-22/detail/detail06.jpg",
      "/products-new/pro-22/detail/detail07.jpg",
      "/products-new/pro-22/detail/detail08.jpg",
      "/products-new/pro-22/detail/detail09.jpg",
      "/products-new/pro-22/detail/detail10.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-23",
    name: "AMI DRAJK 系列新品 23",
    category: Category.HOT,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1280,
    originalPrice: 1540,
    sales: 71,
    isNew: true,
    images: [
      "/products-new/pro-23/main/main01.jpg",
      "/products-new/pro-23/main/main02.jpg",
      "/products-new/pro-23/main/main03.jpg",
      "/products-new/pro-23/main/main04.jpg",
      "/products-new/pro-23/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 23，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-23/detail/detail02.jpg",
      "/products-new/pro-23/detail/detail03.jpg",
      "/products-new/pro-23/detail/detail04.jpg",
      "/products-new/pro-23/detail/detail05.jpg",
      "/products-new/pro-23/detail/detail06.jpg",
      "/products-new/pro-23/detail/detail07.jpg",
      "/products-new/pro-23/detail/detail08.jpg",
      "/products-new/pro-23/detail/detail09.jpg",
      "/products-new/pro-23/detail/detail10.jpg",
      "/products-new/pro-23/detail/detail11.jpg",
      "/products-new/pro-23/detail/detail12.jpg",
      "/products-new/pro-23/detail/detail13.jpg",
      "/products-new/pro-23/detail/detail14.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-24",
    name: "AMI DRAJK 系列新品 24",
    category: Category.NEW,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1010,
    originalPrice: 1480,
    sales: 320,
    isNew: true,
    images: [
      "/products-new/pro-24/main/main01.jpg",
      "/products-new/pro-24/main/main02.jpg",
      "/products-new/pro-24/main/main03.jpg",
      "/products-new/pro-24/main/main04.jpg",
      "/products-new/pro-24/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 24，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-24/detail/detail02.jpg",
      "/products-new/pro-24/detail/detail03.jpg",
      "/products-new/pro-24/detail/detail04.jpg",
      "/products-new/pro-24/detail/detail05.jpg",
      "/products-new/pro-24/detail/detail06.jpg",
      "/products-new/pro-24/detail/detail07.jpg",
      "/products-new/pro-24/detail/detail08.jpg",
      "/products-new/pro-24/detail/detail09.jpg",
      "/products-new/pro-24/detail/detail10.jpg",
      "/products-new/pro-24/detail/detail11.jpg",
      "/products-new/pro-24/detail/detail12.jpg",
      "/products-new/pro-24/detail/detail13.jpg",
      "/products-new/pro-24/detail/detail14.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
  {
    id: "new-25",
    name: "AMI DRAJK 系列新品 25",
    category: Category.RECOMMEND,
    attribute: Attribute.NORMAL,
    fit: Fit.STRAIGHT,
    price: 1368,
    originalPrice: 1920,
    sales: 470,
    isNew: true,
    images: [
      "/products-new/pro-25/main/main01.jpg",
      "/products-new/pro-25/main/main02.jpg",
      "/products-new/pro-25/main/main03.jpg",
      "/products-new/pro-25/main/main04.jpg",
      "/products-new/pro-25/main/main05.jpg",
    ],
    tags: ["新品", "潮流"],
    description: "AMI DRAJK 2024秋冬新款系列 25，采用优质面料，舒适版型。",
    material: "棉/聚酯纤维",
    colors: ["多色可选"],
    sizes: ["S", "M", "L", "XL"],
    detailImages: [
      "/products-new/pro-25/detail/detail02.jpg",
      "/products-new/pro-25/detail/detail03.png",
      "/products-new/pro-25/detail/detail04.jpg",
      "/products-new/pro-25/detail/detail05.jpg",
      "/products-new/pro-25/detail/detail06.jpg",
      "/products-new/pro-25/detail/detail07.jpg",
      "/products-new/pro-25/detail/detail08.jpg",
      "/products-new/pro-25/detail/detail09.jpg",
      "/products-new/pro-25/detail/detail10.jpg",
      "/products-new/pro-25/detail/detail11.jpg",
      "/products-new/pro-25/detail/detail12.jpg",
      "/products-new/pro-25/detail/detail13.jpg",
      "/products-new/pro-25/detail/detail14.jpg",
      "/products-new/pro-25/detail/detail15.jpg",
      "/products-new/pro-25/detail/detail16.jpg",
      "/products-new/pro-25/detail/detail17.jpg",
      "/products-new/pro-25/detail/detail18.jpg",
      "/products-new/pro-25/detail/detail19.jpg",
      "/products-new/pro-25/detail/detail20.jpg",
      "/products-new/pro-25/detail/detail21.jpg",
      "/products-new/pro-25/detail/detail22.jpg",
      "/products-new/pro-25/detail/detail23.jpg",
      "/products-new/pro-25/detail/detail24.jpg",
      "/products-new/pro-25/detail/detail25.jpg",
      "/products-new/pro-25/detail/detail26.jpg",
    ],
    tmallUrl: "https://amidrajk.tmall.com/",
  },
];
